### PR TITLE
Update configuration for flake8 static code analysis tool

### PR DESCRIPTION
**Pull request by vyahello**
Next implementation was added to `.flake8` configuration file:
- max-complexity = 5 (specifies how complex code could be)
- statistics = True (means to print general errors statistic)
- count = True (means how many violations we have)

### CODE REVIEW

**Comment by vyahello** [comment]
@extsoft Seems like `pylint` is failed during building process raising `Unused variable '__class__' (unused-variable)` warning. I guess we need to upgrade `pylint` version to the latest one to fix the issue.

**Comment by extsoft** [comment]
@vyahello please fix #40 first. Once it will be merged, please update your branch.

**Comment by vyahello** [comment]
@extsoft Please take a look first at PR [https://github.com/tatools/demo-python/pull/42](https://github.com/tatools/demo-python/pull/42) to continue working with this PR

**Review by extsoft — APPROVED** [review]

**Comment by extsoft** [comment]
Close #37

**Pull request merged**
