### PR TITLE
Enable D101 rule for pydocstyle

### PR DESCRIPTION
**Pull request by ivan-podorozhnyi**
Added class docstrings to fix violations.

D211 and D212 rules were disabled because there must be chosen 1 out of 2 rules.
For example:
D213: Multi-line docstring summary should start at the second line.
D212: Multi-line docstring summary should start at the first line.

Affects #24

### CODE REVIEW

**Review by AntonKarabaza — CHANGES_REQUESTED** [review]
@ivan-podorozhnyi Please, in commit "Add class docstrings" provide more information about what modules or classes were affected.

**Comment by ivan-podorozhnyi** [comment]
@AntonKarabaza List of classes was added. Please take a look.

**Comment by AntonKarabaza** [comment]
@ivan-podorozhnyi good.

**Review by AntonKarabaza — APPROVED** [review]

**Review by extsoft — APPROVED** [review]
@ivan-podorozhnyi looks good!

**Pull request merged**
