### PR TITLE
Configure flake8

### PR DESCRIPTION
**Pull request by AntonKarabaza**
Add requirements-dev.txt with dev dependencies of project and
configure flake8 as dev dependency.
Modify .travis.yml to install dev dependencies from requirements-dev.txt.
Modify verify_project.sh to invoke flake8 for demo_python_at package
after unit testing.

Affects #6

### CODE REVIEW

**Review by ivan-podorozhnyi — CHANGES_REQUESTED** [review]
@AntonKarabaza Please change you commit message because this (Add requirements-dev.txt add configure flake8 as dev dependecy.) sentence looks strange and not quite clear.

**Comment by AntonKarabaza** [comment]
@ivan-podorozhnyi  Please, take a look at my changes.

**Review by ivan-podorozhnyi — APPROVED** [review]
@AntonKarabaza thank you!

**Review by extsoft — CHANGES_REQUESTED** [review]
@AntonKarabaza I don't see any output from flake on [Travis](https://travis-ci.org/tatools/demo-python/builds/240812167?utm_source=github_status&utm_medium=notification). Are you sure we invoke flake in the correct way? [Looks like no](http://flake8.pycqa.org/en/latest/#using-flake8).

**Comment by AntonKarabaza** [comment]
@extsoft Yes, flake8 gives output only if some violations found. Invoking it without `<version>` runs it for current python's version. I can rewrite invocation in easier format if needed.

**Comment by extsoft** [comment]
> @extsoft Yes, flake8 gives output only if some violations found. Invoking it without <version> runs it for current python's version. I can rewrite invocation in easier format if needed.

@AntonKarabaza I mean you don't specify the package to check.

**Comment by AntonKarabaza** [comment]
> @AntonKarabaza I mean you don't specify the package to check.

@extsoft Without specified package to check it verifies whole project. Are we have to check only `demo_python_at` package?

**Comment by extsoft** [comment]
@AntonKarabaza yes, we have.

**Comment by AntonKarabaza** [comment]
@extsoft Please, take a look now.

**Review by extsoft — APPROVED** [review]

**Pull request merged**
