### PR TITLE
Add `.flake8` configuration file

### PR DESCRIPTION
**Pull request by ivan-podorozhnyi**
Change maximum allowed line length to 120 chars.

Affects #19

### CODE REVIEW

**Review by AntonKarabaza — APPROVED** [review]

**Review by extsoft — CHANGES_REQUESTED** [review]
@ivan-podorozhnyi the goal of your commit is not `Add `.flake8` configuration file`, but `Set max line length to 120 chars`. Am I right?

**Comment by ivan-podorozhnyi** [comment]
@extsoft Yes, you are right. The goal of commit is to change the max line length. But to do this we have to add flake8 configuration file and write configuration inside.
I made commit header shorter because there is a 50 chars limit. This way I divided the header and details of commit. As for me this commit is similar to 4e2d50afc08ca06c40208d6185714da21f7c45a7. Am I mistaken?

**Comment by extsoft** [comment]
@ivan-podorozhnyi A commit explains what we do, but not how we do. Did I mention `.travis.yml` in 4e2d50afc08ca06c40208d6185714da21f7c45a7? 

How we do - I can read from modified files.

**Comment by ivan-podorozhnyi** [comment]
@extsoft Thank you, now it's clear. Changes have been applied. Now commit message is correct.

**Review by extsoft — APPROVED** [review]

**Pull request merged**
